# main.yml
name: Test, Build and Release apk

on:
  push:
    tags:
      - v*

# 这个工作流程需要执行的任务
jobs:
  build-job1:
    runs-on: windows-latest
    steps:
    - name: Checkout Resources
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'beta'
    
    - name: flutter config
      run: flutter config --enable-windows-desktop

    - name: flutter pub get
      run: flutter pub get

    - name: flutter version
      run: flutter --version
    
    - name: flutter build
      run: flutter build windows

    - name: dir
      run: dir .

    - name: dir2
      run: dir ./build/windows/x64/runner/Release/

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          ./build/windows/x64/runner/Release/login_wifi.exe
          


  